assetDir = "assets/build/"
baseURL = "https://sransara.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "sransara"

[permalinks]
  notes = "/:sections/:title/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
