assetDir = "transient/assets/"
baseURL = "https://sransara.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "sransara"

[markup]
  [markup.goldmark]
   [markup.goldmark.extensions]
      footnote = false
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  notes = "/:sections/:title/"
