assetDir = "assets/build/"
baseURL = "https://s.ransara.xyz/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "s.ransara"

[permalinks]
  notes = "/:sections/:title/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true