assetDir = "transient/assets/"
baseURL = "https://sransara.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "sransara"

[permalinks]
  notes = "/:sections/:title/"

[markup.asciidocExt]
    extensions = ["asciidoctor-diagram", "asciidoctor-bibtex", "asciidoctor-latex"]
    workingFolderCurrent = true
    safeMode = "unsafe"
    sectionNumbers = true
    [markup.asciidocExt.attributes]
