name: "Deploy"
on:
  push:
    branches:
      - master
      - draft
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NIXPKGS_ALLOW_UNFREE: 1
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Install nix dependencies
        run: nix-shell --command "echo Hello World"

      - name: Install npm dependencies
        run: nix-shell --command "npm install"
      
      - name: Build and deploy draft
        if: github.ref == 'refs/heads/draft'
        run: |
          nix-shell --command "npm run gulp build"
          nix-shell --command "netlify deploy --dir=public --alias=draft"
        env:
          HUGO_BASEURL: https://draft--sransara-com.netlify.app/

      - name: Build and deploy prod
        if: github.ref == 'refs/heads/master'
        run: |
          nix-shell --command "npm run gulp build"
          nix-shell --command "netlify deploy --dir=public --prod"