name: "Deploy"
on:
  push:
    branches:
      - master
      - draft
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2.3.4

      - name: Install nix
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -r "npm install && npm run gulp build"

      - name: Deploy to netlify production
        if: github.ref == 'refs/heads/draft'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --alias=draft

      - name: Deploy to netlify production
        if: github.ref == 'refs/heads/master'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --alias=prod